name: 'default'

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  checks: 'write' # code_check-style_golangci_lint
  contents: 'write' # delivery-release
  security-events: 'write' # security-sast_codeql (SARIF upload)

jobs:
  default:
    uses: 'rios0rios0/pipelines/.github/workflows/go-binary.yaml@main'
    with:
      binary_name: 'terraform-provider-http'
      gpg_sign: true
    secrets:
      gpg_private_key: '${{ secrets.GPG_PRIVATE_KEY }}'
      gpg_passphrase: '${{ secrets.PASSPHRASE }}'
